api.joke_categories :
    path     : /categories
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::categoryAction

api.joke_random :
    path     : /random
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::randomAction

api.joke_search :
    path     : /search
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::searchAction

api.joke_slack :
    path     : /slack
    methods  : POST
    defaults :
        _controller         : \Chuck\App\Api\Controller\Jokes\SlackController::indexAction
    options  :
        _before_middlewares : \Chuck\App\Api\Middleware\Verification::slackOrigin

api.get_joke :
    path     : /{id}
    methods  : GET
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::getAction

api.update_joke :
    path     : /{id}
    methods  : PUT
    defaults :
        _controller : \Chuck\App\Api\Controller\JokesController::updateAction
    options  :
        _before_middlewares : [ \Chuck\App\Api\Middleware\Authorization::write, \Chuck\App\Api\Middleware\RequestBodyParser::parse ]
